# Generated by Django 6.1.1 on 2026-10-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_DB',
            fields=[
                ('Complaints', models.TextField()),
                ('Vehicle_Name', models.CharField(max_length=10)),
                ('Purchase_Date', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('RC_Number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DL_Number', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='student_DB',
        ),
    ]
